In [1]:
import numpy as np
import pandas as pd

In [2]:
DATA = "data.csv"

In [3]:
df = pd.read_csv(DATA)

In [4]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

# Question 1: Version of NumPy

In [5]:
np.__version__

'1.20.3'

# Question 2: Number of records in the dataset

In [6]:
df.shape[0]

11914

# Question 3: The most popular car manufacturers


In [7]:
df.make.value_counts()[:3]

Chevrolet     1123
Ford           881
Volkswagen     809
Name: make, dtype: int64

In [15]:
df.groupby(["make"]).popularity.mean().sort_values(ascending=False).head()

make
Ford       5657.0
BMW        3916.0
Audi       3105.0
Ferrari    2774.0
Honda      2202.0
Name: popularity, dtype: float64

# Question 4: Number of unique Audi car models


In [10]:
df[df.make == "Audi"].model.nunique()

34

# Question 5: Number of columns with missing values


In [11]:
(df.isna().sum() > 0).sum()

5

# Question 6: Does the median value change after filling missing values?

Find the median value of "Engine Cylinders" column in the dataset.  
Next, calculate the most frequent value of the same "Engine Cylinders".  
Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.  
Now, calculate the median value of "Engine Cylinders" once again.  
Has it changed?  
 
Hint: refer to existing mode and median functions to complete the task.  

In [18]:
ec_median = df.engine_cylinders.median();
ec_median

6.0

In [15]:
most_frequent = df.engine_cylinders.value_counts().index[0]
most_frequent

4.0

In [16]:
engine_cylinders_wout_na = df.engine_cylinders.fillna(most_frequent)

Проверим, что NA точно заполнены

In [19]:
df.engine_cylinders.isna().sum()

30

In [20]:
engine_cylinders_wout_na.isna().sum()

0

In [21]:
engine_cylinders_wout_na.median()

6.0

Ответ: медиана не поменялась, после заполнения пропущенных значений

# Questions 7: Value of the first element of w

Select all the "Lotus" cars from the dataset.  
Select only columns "Engine HP", "Engine Cylinders".  
Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).  
Get the underlying NumPy array. Let's call it X.  
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.  
Invert XTX.  
Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].  
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.  
What's the value of the first element of w?  

Note: You just implemented linear regression. We'll talk about it in the next lesson.  

In [26]:
crop_df = df.loc[df.make == "Lotus",["engine_hp", "engine_cylinders"]]

In [29]:
crop_df.drop_duplicates(inplace=True)

In [36]:
X = crop_df.values

In [67]:
XTX = X.T.dot(X)

In [68]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [38]:
y = np.array([
    1100,
    800,
    750,
    850,
    1300,
    1000,
    1000,
    1300,
    800
])

In [69]:
np.linalg.inv(XTX)

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [70]:
w = np.linalg.inv(XTX).dot(X.T).dot(y)

In [73]:
X.dot(w)

array([ 614.18726905,  747.44066855,  742.84572374, 1099.71608343,
       1456.59197396,  886.81881751, 1203.8700094 ,  926.64351614,
        848.52945437])

In [74]:
w[0]

4.594944810094576

Ответ: w[0] = 4.5949