In [1]:
import numpy as np
import pandas as pd

In [4]:
v = np.arange(10); v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
v = np.linspace(1, 10, 3); v

array([ 1. ,  5.5, 10. ])

In [6]:
v = np.array([1,2,3]); v

array([1, 2, 3])

In [7]:
v = np.array([
    [1,2,4],
    [1,22,4]
]); v

array([[ 1,  2,  4],
       [ 1, 22,  4]])

In [8]:
v[:,1] = np.zeros(1)

In [11]:
v[0,:] = [1]

In [12]:
v

array([[1, 1, 1],
       [1, 0, 4]])

In [13]:
v.T

array([[1, 1],
       [1, 0],
       [1, 4]])

In [14]:
v

array([[1, 1, 1],
       [1, 0, 4]])

In [15]:
v.T[0,:] = 3

In [16]:
v

array([[3, 1, 1],
       [3, 0, 4]])

In [19]:
v

array([[3, 1, 1],
       [3, 0, 4]])

In [20]:
u = np.array([3,10])

In [21]:
u

array([ 3, 10])

In [22]:
v.dot(u)

ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

In [23]:
v.T.dot(u)

array([39,  3, 43])

In [24]:
v.dot(u.T)

ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

In [27]:
display(v.T, u)

array([[3, 3],
       [1, 0],
       [1, 4]])

array([ 3, 10])

In [34]:
def vector_vector_mult(v1, v2):
    assert v1.shape[0] == v2.shape[0]
    return sum(v1 * v2)

In [32]:
[vector_vector_mult(x, u) for x in v.T]

[39, 3, 43]

In [35]:
np.linalg.inv

<function numpy.linalg.inv(a)>

In [36]:
v

array([[3, 1, 1],
       [3, 0, 4]])

In [39]:
vs = v[:,[0,1]]

In [40]:
vs

array([[3, 1],
       [3, 0]])

In [41]:
vsi = np.linalg.inv(vs)

In [42]:
vsi

array([[ 0.        ,  0.33333333],
       [ 1.        , -1.        ]])

In [43]:
vs.dot(vsi)

array([[1., 0.],
       [0., 1.]])

# pandas

In [2]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [3]:
df = pd.DataFrame(data, columns = columns)

In [4]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [5]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [20]:
df.groupby("Transmission Type").MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64