In [26]:
from sklearn.cluster import KMeans
import numpy as np

In [3]:
from sklearn.datasets import make_circles

In [8]:
a = make_circles(10)

In [10]:
k_means = KMeans(n_clusters=3)

In [15]:
y_ = k_means.fit_predict(a[0])

In [17]:
y_,a[1]

(array([0, 0, 2, 2, 2, 0, 1, 0, 2, 1]),
 array([1, 0, 1, 1, 0, 0, 1, 1, 0, 0], dtype=int64))

In [30]:
a[0][3]

array([0.8, 0. ])

In [31]:
to_predict_list = (0.8,0)

In [32]:
to_predict_list = list(map(float, to_predict_list))

In [33]:
to_predict_list

[0.8, 0.0]

In [34]:
to_predict = np.array(to_predict_list).reshape(1,2)

In [35]:
to_predict

array([[0.8, 0. ]])

In [37]:
k_means.predict(to_predict)[0]

2